export {
  CenterLayout,
  DefaultLayout,
  TwoColsLayout,
  TwoColsHeaderLayout,
  ImageLayout,
  ImageRightLayout,
  ImageLeftLayout,
  CoverLayout,
  QuoteLayout,
  SectionLayout,
  type CenterLayoutProps,
  type DefaultLayoutProps,
  type TwoColsLayoutProps,
  type TwoColsHeaderLayoutProps,
  type ImageLayoutProps,
  type ImageRightLayoutProps,
  type ImageLeftLayoutProps,
  type CoverLayoutProps,
  type QuoteLayoutProps,
  type SectionLayoutProps,
} from './layouts';
